import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "#FFFFFF",
        surface: "#f7f9fb",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        "surface-bright": "#f7f9fb",
        "surface-alt": "#F1F5F9",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        primary: "#00647c",
        "primary-container": "#007f9d",
        "primary-fixed": "#b7eaff",
        "primary-fixed-dim": "#6cd3f7",
        "primary-dim": "#2b5d3c",
        "on-primary": "#ffffff",
        "on-primary-container": "#fafdff",
        "on-primary-fixed": "#001f28",
        "on-primary-fixed-variant": "#004e61",
        "inverse-primary": "#6cd3f7",
        "voice-active": "#0891B2",
        "voice-processing": "#0EA5E9",
        "voice-muted": "#CBD5E1",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        outline: "#6e797e",
        "outline-variant": "#bdc8ce",
        "on-surface": "#191c1e",
        "on-surface-variant": "#3e484d",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "error-dim": "#67040d",
        tertiary: "#894e00",
        "tertiary-container": "#a86516",
        "tertiary-fixed": "#ffdcbf",
        "tertiary-fixed-dim": "#ffb873",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3b00",
      },
      fontFamily: {
        headline: ["'DM Sans'", "sans-serif"],
        display: ["'DM Sans'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        label: ["'Open Sans'", "'Inter'", "sans-serif"],
        serif: ["'Literata'", "serif"],
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        margin: "24px",
        "margin-mobile": "20px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
