"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ClipboardList, Users, UserRound, ShieldAlert, Gauge, FileCheck2, Clock3, Upload, Sparkles, ExternalLink, Send } from "lucide-react";
import { api } from "@/lib/api";
import { Badge, Card, DataBadge, Empty, Metric, Page } from "@/app-components/ui";

const date=(v:any)=>v?new Date(v).toLocaleDateString():"—";
const dt=(v:any)=>v?new Date(v).toLocaleString():"—";
const money=(v:any)=>v==null||v===""?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v)||0);
const human=(v:any)=>String(v??"—").replaceAll("_"," ");

function AdjusterDashboard(){const[d,setD]=useState<any>(null),[error,setError]=useState("");useEffect(()=>{api("/api/v1/adjuster/dashboard").then(setD).catch(e=>setError(e.message))},[]);return <Page title="Adjuster overview" subtitle="Operational metrics, assigned workload and SLA health." actions={<Link className="btn primary" href="/adjuster/queue"><ClipboardList size={15}/>Open claims queue</Link>}>{error&&<div className="error">{error}</div>}<div className="metrics"><Metric label="Filed claims" value={d?.total_filed_claims??"—"} note="Tenant workflow" icon={<ClipboardList size={15}/>}/><Metric label="Total users" value={d?.total_users??"—"} note="Active accounts" icon={<Users size={15}/>}/><Metric label="Assigned to me" value={d?.assigned_to_me??"—"} note="Active workload" icon={<UserRound size={15}/>}/><Metric label="SLA breaches" value={d?.sla_breached??"—"} note="Needs escalation" icon={<ShieldAlert size={15}/>}/></div><div className="grid grid-2"><Card><div className="card-title">Operational health</div>{[["Under review",d?.under_review],["Pending evidence",d?.pending_evidence],["Queue total",d?.queue_total]].map(([k,v])=><div className="list-row" key={String(k)}><div className="list-main"><b>{k}</b><span>Current workload</span></div><b>{v??"—"}</b></div>)}<div className="chart">{[d?.under_review||0,d?.pending_evidence||0,d?.assigned_to_me||0,d?.sla_breached||0].map((v:any,i)=> <div className="bar" key={i} style={{height:Math.max(16,Math.min(160,Number(v)*22))}}/>)}</div></Card><Card><div className="card-title">Recent assigned claims</div>{d?.recent_claims?.length?d.recent_claims.slice(0,7).map((c:any)=><div className="list-row" key={c.ticket_id}><div className="list-main"><b>{c.ticket_id}</b><span>{human(c.status)} · {c.age_hours??0}h old</span></div><div className="actions"><DataBadge status={c.status}/><Link className="link" href={"/adjuster/claims/"+c.ticket_id+"/workbench"}>Review</Link></div></div>):<Empty text="No assigned claims are currently available."/>}</Card></div></Page>}

function AdjusterQueue(){const[d,setD]=useState<any>(null),[f,setF]=useState("all"),[error,setError]=useState("");async function load(s=f){setF(s);try{setD(await api("/api/v1/adjuster/queue?status="+s))}catch(e:any){setError(e.message)}}useEffect(()=>{load("all")},[]);return <Page title="Claims Queue" subtitle="Assigned claims with SLA age and recommended next action." actions={<Link className="btn primary" href="/adjuster"><Gauge size={14}/>Overview</Link>}><Card><div className="tabs">{["all","submitted","under_review","pending_evidence","escalated"].map(s=><button className={"tab "+(f===s?"active":"")} key={s} onClick={()=>load(s)}>{human(s)}</button>)}</div>{error&&<div className="error">{error}</div>}{d?.items?.length?<div className="table-wrap"><table><thead><tr><th>Claim</th><th>Status</th><th>Age</th><th>SLA</th><th>Next action</th><th></th></tr></thead><tbody>{d.items.map((c:any)=><tr key={c.ticket_id}><td><b>{c.ticket_id}</b></td><td><DataBadge status={c.status}/></td><td>{c.age_hours??0}h</td><td>{c.sla_breached?<Badge tone="danger">Breached</Badge>:<Badge tone="success">Within SLA</Badge>}</td><td>{human(c.next_action)}</td><td><Link className="link" href={"/adjuster/claims/"+c.ticket_id+"/workbench"}>Review</Link></td></tr>)}</tbody></table></div>:<Empty text="No claims in the selected queue."/>}</Card></Page>}

function Workbench({ticket}:{ticket:string}){const[d,setD]=useState<any>(null),[cop,setCop]=useState<any>(null),[requests,setRequests]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[error,setError]=useState(""),[chat,setChat]=useState(""),[chatRows,setChatRows]=useState<any[]>([]),[request,setRequest]=useState(""),[note,setNote]=useState(""),[decision,setDecision]=useState(""),[rationale,setRationale]=useState(""),[priority,setPriority]=useState("normal"),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const [a,b,c,e]=await Promise.all([api<any>("/api/v1/adjuster/claims/"+ticket),api<any>("/api/v1/adjuster/claims/"+ticket+"/copilot"),api<any>("/api/v1/adjuster/claims/"+ticket+"/evidence-requests"),api<any>("/api/v1/adjuster/claims/"+ticket+"/audit")]);setD(a);setCop(b);setRequests(Array.isArray(c)?c:c.items||[]);setAudit(Array.isArray(e)?e:e.items||[]);setChatRows(b.chat||[]);setPriority(a?.claim?.priority||"normal")}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[ticket]);
 async function act(url:string,body?:any,method:"POST"|"PATCH"="POST"){try{await api(url,{method,body:body?JSON.stringify(body):undefined});await load()}catch(e:any){setError(e.message)}}
 async function ask(){if(!chat.trim())return;const v=chat;setChat("");setChatRows(x=>[...x,{speaker:"adjuster",message:v}]);try{const r=await api<any>("/api/v1/adjuster/claims/"+ticket+"/copilot/chat",{method:"POST",body:JSON.stringify({message:v})});setChatRows(x=>[...x,{speaker:"copilot",message:r.message||r.response||"Copilot response received."}])}catch(e:any){setError(e.message)}}
 if(loading)return <Page title={ticket} subtitle="Loading adjuster dossier…"><Card><div className="empty">Loading claim package and AI analysis…</div></Card></Page>;
 const c=d?.claim||{},facts=d?.extracted_data||{},evidence=d?.evidence||d?.submission_package?.evidence||[],req=d?.requirements||[],missing=[...(d?.missing_requirements||[]),...(d?.missing_evidence||[])],a=cop?.analysis,conf=Number(a?.confidence_score||0)*100;
 async function evidenceUrl(id:string){try{const x=await api<any>("/api/v1/adjuster/claims/"+ticket+"/evidence/"+id+"/url");window.open(x.url,"_blank","noopener,noreferrer")}catch(e:any){setError(e.message)}}
 return <Page title={ticket} subtitle="Human-in-the-loop claim adjudication workbench." actions={<><DataBadge status={c.status||"under_review"}/><button className="btn secondary" onClick={()=>act("/api/v1/adjuster/claims/"+ticket+"/assign")}><UserRound size={14}/>Assign to me</button></>}>{error&&<div className="error">{error}</div>}<div className="metrics"><Metric label="Estimated amount" value={money(c.estimated_claim_amount)} note={c.insurance_type||"Claim"} icon={<FileCheck2 size={15}/>}/><Metric label="Claim age" value={c.updated_at?Math.round((Date.now()-new Date(c.updated_at).getTime())/3600000)+"h":"—"} note="Since last update" icon={<Clock3 size={15}/>}/><Metric label="Evidence items" value={evidence.length} note="Submitted" icon={<Upload size={15}/>}/><Metric label="Copilot confidence" value={a?.confidence_score?Math.round(conf)+"%":"—"} note={a?.decision_recommendation?human(a.decision_recommendation):"Analysis"} icon={<Sparkles size={15}/>}/></div>
 <div className="grid grid-2"><Card><div className="card-title">Claim overview</div><div className="detail-grid"><div className="detail-item"><span>Insurance type</span><b>{c.insurance_type||"—"}</b></div><div className="detail-item"><span>Incident</span><b>{date(c.incident_date||c.event_date)}</b></div><div className="detail-item"><span>Priority</span><b>{priority}</b></div></div><div className="dossier-section"><div className="card-title">Linked policy</div>{d?.policy?<div className="fact-grid"><div className="fact"><small>Policy</small><b>{d.policy.policy_number}</b></div><div className="fact"><small>Coverage</small><b>{money(d.policy.coverage_amount)}</b></div><div className="fact"><small>Deductible</small><b>{money(d.policy.deductible)}</b></div><div className="fact"><small>Validity</small><b>{date(d.policy.effective_date)} – {date(d.policy.expiry_date)}</b></div></div>:<Empty text="No linked policy details found."/>}</div><div className="dossier-section"><div className="card-title">Collected claimant facts</div>{Object.keys(facts).length?<div className="fact-grid">{Object.entries(facts).slice(0,20).map(([k,v])=><div className="fact" key={k}><small>{human(k)}</small><b>{typeof v==="object"?JSON.stringify(v):String(v??"—")}</b></div>)}</div>:<Empty text="No extracted facts returned."/>}</div></Card>
 <Card className="copilot-card"><div className="section-head"><div className="card-title" style={{margin:0}}>AI Copilot report</div><button className="btn" onClick={load}><Sparkles size={13}/>Refresh</button></div>{a?<><div className="recommendation"><DataBadge status={a.decision_recommendation||"review"}/><span className="score">{Math.round(conf)}%</span><span className="kpi-note">confidence</span></div><div className="dossier-section"><b>Executive summary</b><p>{a.executive_summary||"—"}</p><b>Decision rationale</b><p>{a.decision_rationale||"—"}</p></div><div className="grid grid-2"><div><b>Coverage observations</b>{(a.coverage_observations||[]).slice(0,4).map((x:string,i:number)=><div className="list-row" key={i}><span>{x}</span></div>)}</div><div><b>Risk flags</b>{(a.risk_flags||[]).slice(0,4).map((x:string,i:number)=><div className="list-row" key={i}><span>{x}</span></div>)}</div></div><div className="dossier-section"><b>Recommended next steps</b>{(a.recommended_next_steps||[]).slice(0,5).map((x:string,i:number)=><div className="list-row" key={i}><span>{i+1}. {x}</span></div>)}</div><div className="dossier-section"><b>Grounding sources</b>{(a.citations||cop?.sources||[]).slice(0,8).map((s:any,i:number)=><div className="list-row" key={i}><div className="list-main"><b>{s.citation_label||s.source_name||s.chunk_id||"Source"}</b><span>{s.page_number?"p. "+s.page_number+" · ":""}{s.clause_number?"Clause "+s.clause_number+" · ":""}{s.document_version?"v"+s.document_version:""}</span></div></div>)}</div></>:<Empty text={cop?.error||"Copilot analysis unavailable."}/>}</Card></div>
 <div className="grid grid-2 dossier-section"><Card><div className="card-title">Policy verification</div>{Object.keys(d?.policy_verification||{}).length?Object.entries(d.policy_verification).map(([k,v])=><div className="list-row" key={k}><div className="list-main"><b>{human(k)}</b><span>{typeof v==="object"?JSON.stringify(v):String(v??"—")}</span></div></div>):<Empty text="No policy verification details returned."/>}<div className="dossier-section"><div className="card-title">Knowledge sources</div>{d?.knowledge_sources?.length?d.knowledge_sources.slice(0,6).map((s:any,i:number)=><div className="list-row" key={s.id||i}><div className="list-main"><b>{s.title||s.source_name||"Policy / regulation source"}</b><span>{s.citation_label||s.snippet||s.content||""}</span></div></div>):<Empty text="No knowledge citations returned."/>}</div></Card><Card><div className="card-title">Filing conversation</div>{d?.conversation?.length?d.conversation.map((m:any,i:number)=><div className="timeline-item" key={i}><span className="timeline-dot"/><div className="timeline-card"><small>{m.speaker} · {dt(m.timestamp)}</small><p>{m.text||m.message}</p></div></div>):<Empty text="No claimant conversation recorded."/>}</Card></div><Card className="dossier-section"><div className="card-title">Submission package</div>{d?.submission_package?<pre style={{whiteSpace:"pre-wrap",fontSize:12,margin:0}}>{JSON.stringify(d.submission_package,null,2)}</pre>:<Empty text="Submission package not available."/>}</Card> <div className="grid grid-2 dossier-section"><Card><div className="section-head"><div className="card-title" style={{margin:0}}>Evidence</div><Badge tone="info">{evidence.length} items</Badge></div>{evidence.length?<div className="table-wrap"><table><thead><tr><th>Document</th><th>Status</th><th>Type</th><th></th></tr></thead><tbody>{evidence.map((x:any,i:number)=><tr key={x.id||i}><td><b>{x.original_filename||x.filename||"Evidence "+(i+1)}</b></td><td><DataBadge status={x.verification_status||x.status||"review"}/></td><td>{x.content_type||x.requested_evidence_type||"Document"}</td><td>{x.id&&<button className="btn" onClick={()=>evidenceUrl(String(x.id))}><ExternalLink size={12}/>View</button>}</td></tr>)}</tbody></table></div>:<Empty text="No evidence attached."/>}</Card>
 <Card><div className="card-title">Requirements & gaps</div>{req.length?req.slice(0,12).map((r:any,i:number)=><div className="list-row" key={r.key||r.id||i}><div className="list-main"><b>{r.label||r.name||r.description||"Requirement"}</b><span>{r.condition||""}</span></div><DataBadge status={r.status||"review"}/></div>):<Empty text="No structured requirements returned."/>}{missing.length>0&&<div className="notice" style={{marginTop:10}}>{missing.length} item(s) still require attention.</div>}</Card></div>
 <div className="grid grid-2 dossier-section"><Card><div className="card-title">Request more information</div><label>Evidence or clarification<textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="Describe what the claimant must provide…"/></label><button className="btn primary" onClick={()=>{if(request.trim())act("/api/v1/adjuster/claims/"+ticket+"/evidence-requests",{request_text:request}).then(()=>setRequest(""))}} disabled={!request.trim()}><Send size={13}/>Send request</button>{requests.map((r:any)=><div className="list-row" key={r.id}><div className="list-main"><b>{r.request_text}</b><span>{human(r.status)}{r.responded_at?" · Responded "+dt(r.responded_at):""}</span>{r.response_note&&<span style={{whiteSpace:"normal"}}>Claimant response: {r.response_note}</span>}{r.response_evidence&&<span>Attachment: {r.response_evidence.name} · {human(r.response_evidence.verification_status||"review")}</span>}</div><DataBadge status={r.status||"open"}/></div>)}</Card>
 <Card><div className="card-title">Decision & notes</div><div className="form-grid"><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">Select</option><option value="approve">Approve</option><option value="partial_approve">Partial approve</option><option value="reject">Reject</option><option value="request_evidence">Request evidence</option><option value="escalate">Escalate</option></select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></label></div><label style={{marginTop:10}}>Rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Record the human decision rationale…"/></label><div className="actions"><button className="btn primary" onClick={()=>decision&&act("/api/v1/adjuster/claims/"+ticket+"/decision",{decision,rationale:rationale||"Decision recorded after claim package review."})} disabled={!decision}>Record decision</button><button className="btn" onClick={()=>act("/api/v1/adjuster/claims/"+ticket,{priority},"PATCH")}>Save priority</button></div><label className="dossier-section">Internal note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Private work note…"/></label><button className="btn" onClick={()=>note&&act("/api/v1/adjuster/claims/"+ticket+"/notes",{note,visibility:"internal"}).then(()=>setNote(""))} disabled={!note.trim()}>Add internal note</button></Card></div>
 <div className="grid grid-2 dossier-section"><Card className="copilot-card"><div className="card-title">Copilot conversation</div><div className="chat-body" style={{minHeight:260}}>{chatRows.length?chatRows.slice(-10).map((m:any,i:number)=><div key={i} className={"message "+((m.speaker||m.role)==="adjuster"?"user":"")}><div className="message-role">{m.speaker||m.role||"copilot"}</div><div className="message-bubble">{m.message||m.content||m.text}</div>{m.citations?.length&&<div className="citation-wrap"><span className="citation-toggle">Sources ({m.citations.length})</span></div>}</div>):<Empty text="Ask about coverage, evidence, risk, or next steps."/>}</div><div className="composer"><textarea value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask the adjuster Copilot…"/><button className="btn primary" onClick={ask} disabled={!chat.trim()}><Send size={13}/>Ask</button></div></Card><Card><div className="card-title">Workflow audit</div>{audit.length?audit.slice(0,12).map((x:any,i:number)=><div className="list-row" key={x.id||i}><div className="list-main"><b>{x.event_type||x.action||"Event"}</b><span>{dt(x.created_at)} {x.reason?"· "+x.reason:""}</span></div></div>):<Empty text="No audit events."/>}</Card></div></Page>}

export { AdjusterDashboard, AdjusterQueue, Workbench };
