"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ClipboardList, Pencil, Plus, ShieldCheck, Trash2, UserRound, Users, X } from "lucide-react";
import { api } from "@/lib/api";
import { Badge, Card, DataBadge, Empty, Metric, Page } from "@/app-components/ui";

const dt=(v:any)=>v?new Date(v).toLocaleString():"—";
const money=(v:any)=>v==null||v===""?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v)||0);
const human=(v:any)=>String(v??"—").replaceAll("_"," ");

function AdminDashboard(){
 const[a,setA]=useState<any[]>([]),[p,setP]=useState<any[]>([]),[c,setC]=useState<any[]>([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([api<any>("/api/v1/admin/adjusters"),api<any>("/api/v1/admin/policies"),api<any>("/api/v1/admin/claims")]).then(([x,y,z])=>{setA(x.items||x);setP(y.items||y);setC(z.items||z)}).catch(e=>setError(e.message))},[]);
 const statusCounts=c.reduce((m,x)=>{m[x.status]=(m[x.status]||0)+1;return m},{} as Record<string,number>);
 return <Page title="Administration" subtitle="Policy inventory, adjuster onboarding and operational control." actions={<Link className="btn primary" href="/admin"><Users size={14}/>Manage administration</Link>}>
  {error&&<div className="error" role="alert">{error}</div>}
  <div className="metrics">
   <Metric label="Policies" value={p.length} note="Inventory" icon={<ShieldCheck size={14}/>}/>
   <Metric label="Adjusters" value={a.length} note={"Active "+a.filter(x=>x.is_active!==false).length} icon={<Users size={14}/>}/>
   <Metric label="Filed claims" value={c.filter(x=>x.status!=="draft").length} note="Tenant workflow" icon={<ClipboardList size={14}/>}/>
   <Metric label="Unassigned" value={c.filter(x=>!x.assigned_adjuster_id&&x.status!=="draft").length} note="Needs routing" icon={<UserRound size={14}/>}/>
  </div>
  <div className="grid grid-2">
   <Card><div className="card-title">Claims by status</div>{Object.keys(statusCounts).length?Object.entries(statusCounts).sort(([,a],[,b])=>(b as number)-(a as number)).map(([k,v])=><div className="list-row" key={k}><div className="list-main"><b>{human(k)}</b><span>Current claims</span></div><b>{String(v)}</b></div>):<Empty text="No claims found."/>}</Card>
   <Card><div className="card-title">Adjuster workload</div>{a.length?a.map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.name}</b><span>{human(x.specialization)} · {x.is_active===false?"Inactive":"Active"}</span></div><b>{x.claims_assigned||0}</b></div>):<Empty text="No adjusters onboarded yet."/>}</Card>
  </div>
 </Page>
}

function Admin(){
 const[a,setA]=useState<any[]>([]),[p,setP]=useState<any[]>([]),[invites,setInvites]=useState<any[]>([]),[mode,setMode]=useState<"adjuster"|"policy"|null>(null),[adjusterFilter,setAdjusterFilter]=useState("all"),[policyTypeFilter,setPolicyTypeFilter]=useState("all"),[policyStatusFilter,setPolicyStatusFilter]=useState("all"),[edit,setEdit]=useState<any>(null),[notice,setNotice]=useState(""),[error,setError]=useState(""),[inviteUrl,setInviteUrl]=useState(""),[importErrors,setImportErrors]=useState<any[]>([]);
 const[form,setForm]=useState<any>({name:"",email:"",phone:"",specialization:"motor",policy_number:"",policy_type:"motor",coverage_amount:"",deductible:"0",effective_date:"",expiry_date:"",policyholder_name:"",policyholder_dob:"",policyholder_phone:"",policyholder_email:""});
 async function load(){const[x,y,z]=await Promise.all([api<any>("/api/v1/admin/adjusters"),api<any>("/api/v1/admin/policies"),api<any>("/api/v1/admin/adjusters/invitations")]);setA(x.items||x);setP(y.items||y);setInvites(z.items||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 function open(m:"adjuster"|"policy",x?:any){setMode(m);setEdit(x||null);setNotice("");setError("");setInviteUrl("");setForm(x?{...form,...x,policyholder_name:x.policyholder_name||"",policyholder_dob:x.policyholder_dob||"",policyholder_phone:x.policyholder_phone||"",policyholder_email:x.policyholder_email||""}:{name:"",email:"",phone:"",specialization:"motor",policy_number:"",policy_type:"motor",coverage_amount:"",deductible:"0",effective_date:"",expiry_date:"",policyholder_name:"",policyholder_dob:"",policyholder_phone:"",policyholder_email:""})}
 async function invite(){setNotice("");setError("");try{const r=await api<any>("/api/v1/admin/adjusters/invite",{method:"POST",body:JSON.stringify({name:form.name,email:form.email,phone:form.phone,specialization:form.specialization})});setInviteUrl(r.invitation_url||"");setNotice("Invitation queued for delivery. Use the onboarding link while the email is pending.");await load()}catch(e:any){setError(e.message)}}
 async function resendInvitation(id:string){setNotice("");setError("");try{const r=await api<any>("/api/v1/admin/adjusters/invitations/"+encodeURIComponent(id)+"/resend",{method:"POST"});setInviteUrl(r.invitation_url||"");setNotice("A fresh invitation was queued for delivery.");await load()}catch(e:any){setError(e.message)}}
 async function savePolicy(){setNotice("");setError("");try{if(edit)await api("/api/v1/admin/policies/"+edit.id,{method:"PUT",body:JSON.stringify({policy_type:form.policy_type,coverage_amount:Number(form.coverage_amount),deductible:Number(form.deductible),effective_date:form.effective_date,expiry_date:form.expiry_date,policyholder_name:form.policyholder_name,policyholder_dob:form.policyholder_dob,policyholder_phone:form.policyholder_phone,policyholder_email:form.policyholder_email})});else await api("/api/v1/admin/policies/strict",{method:"POST",body:JSON.stringify({policy_number:form.policy_number,policy_type:form.policy_type,coverage_amount:Number(form.coverage_amount),deductible:Number(form.deductible),effective_date:form.effective_date,expiry_date:form.expiry_date,policyholder_name:form.policyholder_name,policyholder_dob:form.policyholder_dob,policyholder_phone:form.policyholder_phone,policyholder_email:form.policyholder_email||undefined})});setNotice("Policy saved.");setMode(null);await load()}catch(e:any){setError(e.message)}}
 async function importPolicies(e:any){const f=e.target.files?.[0];if(!f)return;setNotice("");setError("");setImportErrors([]);const fd=new FormData();fd.append("file",f);try{const r=await api<any>("/api/v1/admin/policies/import-strict",{method:"POST",body:fd});setNotice("Processed "+(r.total_processed??0)+" policies.");setImportErrors(r.errors||[]);await load()}catch(x:any){setError(x.message)}finally{e.target.value=""}}
 async function downloadFile(path:string,filename:string){try{const token=localStorage.getItem("access_token");const res=await fetch((process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000")+path,{headers:token?{Authorization:"Bearer "+token}:{}});if(!res.ok)throw Error("Download failed ("+res.status+")");const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}catch(e:any){setError(e.message)}}
 async function toggle(id:string,active:boolean){try{await api("/api/v1/admin/adjusters/"+id,{method:"PUT",body:JSON.stringify({is_active:active})});await load()}catch(e:any){setError(e.message)}}
 async function delPolicy(id:string){if(!confirm("Delete this policy?"))return;try{await api("/api/v1/admin/policies/"+encodeURIComponent(id),{method:"DELETE"});await load()}catch(e:any){setError(e.message)}}
 return <Page title="Administration" subtitle="Manage invitations, policy inventory and bulk imports.">
  {(notice||error)&&<div className={error?"error":"notice"} role={error?"alert":"status"}>{error||notice}</div>}
  {inviteUrl&&<Card className="dossier-section"><div className="card-title">Adjuster onboarding link</div><div className="composer"><input value={inviteUrl} readOnly/><button className="btn" onClick={()=>navigator.clipboard?.writeText(inviteUrl)}>Copy</button></div><div className="card-kicker" style={{marginTop:8}}>The link expires automatically and completes password + passkey setup before operational access.</div></Card>}
  <div className="actions dossier-section"><button className="btn primary" onClick={()=>open("adjuster")}><Plus size={13}/>Invite adjuster</button><button className="btn" onClick={()=>open("policy")}><Plus size={13}/>Add policy</button><label className="btn">Import CSV/XLSX<input type="file" accept=".csv,.xlsx" hidden onChange={importPolicies}/></label><button className="btn" onClick={()=>downloadFile("/api/v1/admin/policies/template?format=csv","policy-import-template.csv")}>Download policy template</button><label className="btn">Adjuster export<select value={adjusterFilter} onChange={e=>setAdjusterFilter(e.target.value)}><option value="all">All</option><option value="true">Active</option><option value="false">Inactive</option></select></label><button className="btn" onClick={()=>downloadFile("/api/v1/admin/adjusters/export?format=csv"+(adjusterFilter!=="all"?"&is_active="+adjusterFilter:""),"adjusters-export.csv")}>Export adjusters</button><label className="btn">Policy export<select value={policyTypeFilter} onChange={e=>setPolicyTypeFilter(e.target.value)}><option value="all">All types</option>{["motor","health","senior_health","home","travel","cyber"].map(x=><option key={x} value={x}>{x}</option>)}</select><select value={policyStatusFilter} onChange={e=>setPolicyStatusFilter(e.target.value)}><option value="all">All status</option><option value="true">Active</option><option value="false">Inactive</option></select></label><button className="btn" onClick={()=>downloadFile("/api/v1/admin/policies/export?format=csv"+(policyTypeFilter!=="all"?"&policy_type="+policyTypeFilter:"")+(policyStatusFilter!=="all"?"&is_active="+policyStatusFilter:""),"policies-export.csv")}>Export policies</button></div>
  {importErrors.length?<Card className="dossier-section"><div className="card-title">Import validation errors</div>{importErrors.slice(0,50).map((x:any,i:number)=><div className="list-row" key={i}><div className="list-main"><b>Row {x.row}</b><span>{x.policy_number||"—"}</span></div><span className="error" style={{padding:"4px 7px"}}>{x.error}</span></div>)}</Card>:null}
  <div className="grid grid-2 dossier-section">
   <Card><div className="section-head"><div className="card-title" style={{margin:0}}>Adjusters</div><Badge tone="info">{a.length}</Badge></div>{a.length?a.map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.name}</b><span>{x.email} · {human(x.specialization)} · {x.claims_assigned||0} assigned</span></div><div className="actions"><DataBadge status={x.is_active===false?"inactive":"active"}/><button className="btn" onClick={()=>toggle(x.id,x.is_active===false)}>{x.is_active===false?"Activate":"Deactivate"}</button></div></div>):<Empty text="No adjusters found."/>}</Card>
   <Card><div className="section-head"><div className="card-title" style={{margin:0}}>Invitations</div><Badge tone="info">{invites.length}</Badge></div>{invites.length?invites.slice(0,8).map(x=><div className="list-row" key={x.id}><div className="list-main"><b>{x.name}</b><span>{x.email} · {human(x.specialization)}</span><span>Delivery: {human(x.email_delivery_status||"not_queued")} · {x.email_delivery_attempts||0} attempts</span></div><div className="actions"><DataBadge status={x.status}/>{x.status!=="accepted"&&<button className="btn" onClick={()=>resendInvitation(x.id)}>Resend</button>}</div></div>):<Empty text="No outstanding invitations."/>}</Card>
  </div>
  <Card className="dossier-section"><div className="section-head"><div className="card-title" style={{margin:0}}>Policy inventory</div><Badge tone="info">{p.length}</Badge></div>{p.length?<div className="table-wrap"><table><thead><tr><th>Policy</th><th>Type</th><th>Holder</th><th>Coverage</th><th>Status</th><th/></tr></thead><tbody>{p.slice(0,50).map(x=><tr key={x.id}><td><b>{x.policy_number}</b></td><td>{human(x.policy_type)}</td><td>{x.policyholder_name||"—"}</td><td>{money(x.coverage_amount)}</td><td><DataBadge status={x.is_active===false?"inactive":"active"}/></td><td><div className="actions"><button className="btn" onClick={()=>open("policy",x)}><Pencil size={12}/></button><button className="btn" onClick={()=>delPolicy(x.id)}><Trash2 size={12}/></button></div></td></tr>)}</tbody></table></div>:<Empty text="No policies found."/>}</Card>
  {mode==="adjuster"?<Card className="dossier-section"><div className="section-head"><div className="card-title" style={{margin:0}}>Invite adjuster</div><button className="icon-btn" onClick={()=>setMode(null)}><X size={14}/></button></div><div className="form-grid"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>Specialization<select value={form.specialization} onChange={e=>setForm({...form,specialization:e.target.value})}>{["motor","health","senior_health","home","travel","cyber"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="actions" style={{marginTop:14}}><button className="btn primary" onClick={invite}>Send invitation</button><button className="btn" onClick={()=>setMode(null)}>Cancel</button></div></Card>:null}
  {mode==="policy"?<Card className="dossier-section"><div className="section-head"><div className="card-title" style={{margin:0}}>{edit?"Edit":"Add"} policy</div><button className="icon-btn" onClick={()=>setMode(null)}><X size={14}/></button></div><div className="form-grid"><label>Policy number<input value={form.policy_number||""} onChange={e=>setForm({...form,policy_number:e.target.value})} disabled={!!edit} required/></label><label>Policy type<select value={form.policy_type||"motor"} onChange={e=>setForm({...form,policy_type:e.target.value})}>{["motor","health","senior_health","home","travel","cyber"].map(x=><option key={x}>{x}</option>)}</select></label><label>Coverage amount<input type="number" value={form.coverage_amount||""} onChange={e=>setForm({...form,coverage_amount:e.target.value})} required/></label><label>Deductible<input type="number" value={form.deductible||"0"} onChange={e=>setForm({...form,deductible:e.target.value})} required/></label><label>Effective<input type="date" value={form.effective_date||""} onChange={e=>setForm({...form,effective_date:e.target.value})} required/></label><label>Expiry<input type="date" value={form.expiry_date||""} onChange={e=>setForm({...form,expiry_date:e.target.value})} required/></label><label>Policyholder name<input value={form.policyholder_name||""} onChange={e=>setForm({...form,policyholder_name:e.target.value})} required/></label><label>Date of birth<input type="date" value={form.policyholder_dob||""} onChange={e=>setForm({...form,policyholder_dob:e.target.value})} required/></label><label>Phone number<input value={form.policyholder_phone||""} onChange={e=>setForm({...form,policyholder_phone:e.target.value})} required/></label><label>Email (optional)<input type="email" value={form.policyholder_email||""} onChange={e=>setForm({...form,policyholder_email:e.target.value})}/></label></div><div className="actions" style={{marginTop:14}}><button className="btn primary" onClick={savePolicy}>Save policy</button><button className="btn" onClick={()=>setMode(null)}>Cancel</button></div></Card>:null}
 </Page>
}

function AdminClaims(){
 const[rows,setRows]=useState<any[]>([]),[adjusters,setAdjusters]=useState<any[]>([]),[filter,setFilter]=useState("all"),[targets,setTargets]=useState<Record<string,string>>({}),[reason,setReason]=useState("Operational reassignment"),[error,setError]=useState("");
 async function load(){const[r,a]=await Promise.all([api<any>("/api/v1/admin/claims"+(filter!=="all"?"?status="+encodeURIComponent(filter):"")),api<any>("/api/v1/admin/adjusters")]);setRows(r.items||[]);setAdjusters(a.items||a)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[filter]);
 async function reassign(ticket:string){const target=targets[ticket];if(!target){setError("Select an active adjuster first.");return}try{await api("/api/v1/admin/claims/"+encodeURIComponent(ticket)+"/reassign",{method:"POST",body:JSON.stringify({adjuster_id:target,reason})});await load()}catch(e:any){setError(e.message)}}
 return <Page title="Claims" subtitle="Tenant-wide claim routing and reassignment.">{error&&<div className="error" role="alert">{error}</div>}<Card><div className="actions"><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="submitted">Submitted</option><option value="pending_adjuster">Pending adjuster</option><option value="under_review">Under review</option><option value="pending_evidence">Pending evidence</option><option value="escalated">Escalated</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="closed">Closed</option></select></label><label style={{minWidth:260}}>Reassignment reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label></div></Card><Card className="dossier-section">{rows.length?<div className="table-wrap"><table><thead><tr><th>Claim</th><th>Status</th><th>Type</th><th>Adjuster</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.ticket_id}><td><b>{x.ticket_id}</b></td><td><DataBadge status={x.status}/></td><td>{human(x.insurance_type)}</td><td>{x.assigned_adjuster_name||"Unassigned"}</td><td><div className="actions"><select value={targets[x.ticket_id]||x.assigned_adjuster_id||""} onChange={e=>setTargets({...targets,[x.ticket_id]:e.target.value})}><option value="">Select</option>{adjusters.filter(a=>a.is_active!==false).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button className="btn primary" onClick={()=>reassign(x.ticket_id)}>Reassign</button></div></td></tr>)}</tbody></table></div>:<Empty text="No claims match this filter."/>}</Card></Page>
}

function Audit(){const[x,setX]=useState<any[]>([]);useEffect(()=>{api<any>("/api/v1/admin/audit/events").then(v=>setX(Array.isArray(v)?v:v.items||[]))},[]);return <Page title="System Audit" subtitle="Administrative events, claim actions and AI decisions."><Card>{x.length?x.slice(0,100).map((r:any,i:number)=><div className="list-row" key={r.id||i}><div className="list-main"><b>{r.event_type||r.action||"Event"}</b><span>{dt(r.created_at)} · {r.reason||r.resource_type||""}</span></div><DataBadge status={r.status||"recorded"}/></div>):<Empty text="No audit events found."/>}</Card></Page>}

export { AdminDashboard, Admin, AdminClaims, Audit };
