"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronRight, Plus, Send, Upload } from "lucide-react";
import { api } from "@/lib/api";
import { Badge, Button, Card, DataBadge, Empty, Page } from "@/app-components/ui";

const date=(v:any)=>v?new Date(v).toLocaleDateString():"—";
const dt=(v:any)=>v?new Date(v).toLocaleString():"—";
const money=(v:any)=>v==null||v===""?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v)||0);
const human=(v:any)=>String(v??"—").replaceAll("_"," ");

function Policies(){const[x,setX]=useState<any[]>([]);useEffect(()=>{api<any>("/api/v1/policies/my-policies").then(v=>setX(Array.isArray(v)?v:v.items||[]))},[]);return <Page title="Policies" subtitle="Policies linked to your account." actions={<Link className="btn primary" href="/policies/link"><Plus size={14}/>Link policy</Link>}><Card>{x.length?<div className="table-wrap"><table><thead><tr><th>Policy</th><th>Type</th><th>Status</th><th>Effective</th></tr></thead><tbody>{x.map(p=><tr key={p.id||p.policy_number}><td><b>{p.policy_number}</b></td><td>{p.insurance_type||p.policy_type||"—"}</td><td><Badge tone={p.is_active===false?"neutral":"success"}>{p.is_active===false?"Inactive":"Active"}</Badge></td><td>{date(p.effective_date)}</td></tr>)}</tbody></table></div>:<Empty text="No policies linked yet."/>}</Card></Page>}

function LinkPolicy(){const[f,setF]=useState({policy_number:"",policyholder_name:"",date_of_birth:"",phone_last4:""}),[msg,setMsg]=useState(""),[error,setError]=useState("");async function s(e:FormEvent){e.preventDefault();try{await api("/api/v1/policies/link",{method:"POST",body:JSON.stringify({...f,policyholder_name:f.policyholder_name||undefined})});setMsg("Policy linked successfully.")}catch(e:any){setError(e.message)}}return <Page title="Link a policy" subtitle="Verify policy ownership using the required details."><Card><form className="form" onSubmit={s}><div className="form-grid">{Object.entries(f).map(([k,v])=><label key={k}>{human(k)}<input type={k==="date_of_birth"?"date":k==="phone_last4"?"text":"text"} value={String(v)} onChange={e=>setF({...f,[k]:e.target.value})} required={k!=="policyholder_name"} /></label>)}</div>{error&&<div className="error">{error}</div>}{msg&&<div className="notice">{msg}</div>}<button className="btn primary">Verify and link</button></form></Card></Page>}

function Claims(){const[x,setX]=useState<any[]>([]);useEffect(()=>{api<any>("/api/v1/claims").then(v=>setX(Array.isArray(v)?v:v.items||[]))},[]);return <Page title="Claims" subtitle="Filed and active insurance claims." actions={<Link className="btn" href="/track">Track all claims</Link>}><Card>{x.length?<div className="table-wrap"><table><thead><tr><th>Claim</th><th>Status</th><th>Incident</th><th>Updated</th><th></th></tr></thead><tbody>{x.map(c=><tr key={c.ticket_id}><td><b>{c.ticket_id}</b></td><td><DataBadge status={c.status}/></td><td>{date(c.incident_date||c.event_date)}</td><td>{dt(c.updated_at)}</td><td><Link className="link" href={"/claims/"+c.ticket_id}>Open</Link></td></tr>)}</tbody></table></div>:<Empty text="No claims found."/>}</Card></Page>}

function Track(){const[d,setD]=useState<any>(null),[error,setError]=useState("");useEffect(()=>{api("/api/v1/claims/track").then(setD).catch(e=>setError(e.message))},[]);async function discard(t:string){if(!confirm("Discard this draft claim?"))return;try{await api("/api/v1/claims/"+t,{method:"DELETE"});setD((v:any)=>({...v,items:(v.items||[]).filter((x:any)=>x.ticket_id!==t)}))}catch(e:any){setError(e.message)}}return <Page title="Track claims" subtitle="Workflow status, evidence requests and adjuster updates.">{error&&<div className="error">{error}</div>}<Card>{d?.items?.length?d.items.map((c:any)=><div className="list-row" key={c.ticket_id}><div className="list-main"><b>{c.ticket_id}</b><span>{c.open_request_count||0} open evidence request(s) · Updated {dt(c.updated_at)}</span></div><div className="actions"><DataBadge status={c.status}/><Link className="btn" href={"/claims/"+c.ticket_id}>Open</Link>{!["submitted","closed","rejected"].includes(c.status)&&<Button onClick={()=>discard(c.ticket_id)}>Discard</Button>}</div></div>):<Empty text="No tracked claims yet."/>}</Card></Page>}

function ClaimDetail({ticket}:{ticket:string}){const[d,setD]=useState<any>(null),[error,setError]=useState("");useEffect(()=>{api("/api/v1/claims/"+ticket).then(setD).catch(e=>setError(e.message))},[ticket]);if(!d)return <Page title={ticket} subtitle="Loading claim dossier…"><Card><div className="empty">Loading…</div></Card></Page>;const c=d.claim||d,p=d.pipeline_state||{},req=p.evidence_requests||d.evidence_requests||[],facts=d.extracted_data||p.extracted_data||{};return <Page title={ticket} subtitle="Claim status, evidence requests and claimant workflow." actions={<Link className="btn" href={"/claims/"+ticket+"/evidence"}><Upload size={14}/>Evidence</Link>}><div className="detail-grid"><div className="detail-item"><span>Status</span><b><DataBadge status={c.status||"unknown"}/></b></div><div className="detail-item"><span>Insurance type</span><b>{c.insurance_type||"—"}</b></div><div className="detail-item"><span>Incident date</span><b>{date(c.incident_date||c.event_date)}</b></div></div>{error&&<div className="error dossier-section">{error}</div>}<div className="grid grid-2 dossier-section"><Card><div className="card-title">Collected details</div><div className="fact-grid">{Object.entries(facts).slice(0,18).map(([k,v])=><div className="fact" key={k}><small>{human(k)}</small><b>{typeof v==="object"?JSON.stringify(v):String(v??"—")}</b></div>)}</div></Card><Card><div className="card-title">Adjuster requests</div>{req.length?req.map((r:any)=><div className="list-row" key={r.id||r.request_id}><div className="list-main"><b>{r.request_text||r.description||"Information requested"}</b><span>{human(r.status||"open")} {r.due_at?"· Due "+date(r.due_at):""}</span></div><Link className="link" href={"/claims/"+ticket+"/messages"}>Respond</Link></div>):<Empty text="No outstanding adjuster requests."/>}</Card></div><Card className="dossier-section"><div className="section-head"><div className="card-title" style={{margin:0}}>Conversation</div><Link className="link" href={"/claims/"+ticket+"/messages"}>Requests & replies <ChevronRight size={14}/></Link></div>{d.conversation?.length?d.conversation.slice(-10).map((m:any,i:number)=><div className="timeline-item" key={i}><span className="timeline-dot"/><div className="timeline-card"><small>{m.speaker} · {dt(m.timestamp)}</small><p>{m.text||m.message}</p></div></div>):<Empty text="No conversation turns available."/>}</Card></Page>}

function Evidence({ticket}:{ticket:string}){const[d,setD]=useState<any>(null),[error,setError]=useState(""),[note,setNote]=useState(""),[files,setFiles]=useState<Record<string,File|null>>({});useEffect(()=>{api("/api/v1/claims/"+ticket).then(setD).catch(e=>setError(e.message))},[ticket]);const req=(d?.pipeline_state?.evidence_requests||d?.evidence_requests||[]).filter((x:any)=>x.status==="open");async function send(r:any){const fd=new FormData();if(note.trim())fd.append("response_note",note);const file=files[String(r.id||r.request_id)];if(file)fd.append("file",file);try{await api("/api/v1/claims/"+ticket+"/requests/"+(r.id||r.request_id)+"/respond",{method:"POST",body:fd});setNote("");setD(await api("/api/v1/claims/"+ticket))}catch(e:any){setError(e.message)}}return <Page title="Claim evidence" subtitle="Respond to evidence requests from the assigned adjuster.">{error&&<div className="error">{error}</div>}<Card>{req.length?req.map((r:any)=><div className="dossier-section" key={r.id||r.request_id}><div className="section-head"><div className="list-main"><b>{r.request_text||r.description||"Information requested"}</b><span>{r.due_at?"Due "+date(r.due_at):"No due date"}</span></div><Badge tone="warning">Open</Badge></div><label>Response note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Provide context for the adjuster…"/></label><div className="actions" style={{marginTop:10}}><label className="btn">Attach<input type="file" hidden onChange={e=>setFiles({...files,[String(r.id||r.request_id)]:e.target.files?.[0]||null})}/></label><button className="btn primary" onClick={()=>send(r)} disabled={!note.trim()&&!files[String(r.id||r.request_id)]}><Send size={14}/>Submit response</button></div></div>):<Empty text="No outstanding evidence requests."/>}</Card></Page>}

function Messages({ticket}:{ticket:string}){const[d,setD]=useState<any>(null),[error,setError]=useState(""),[notes,setNotes]=useState<Record<string,string>>({}),[files,setFiles]=useState<Record<string,File|null>>({});useEffect(()=>{api("/api/v1/claims/"+ticket).then(setD).catch(e=>setError(e.message))},[ticket]);const req=d?.pipeline_state?.evidence_requests||d?.evidence_requests||[];async function respond(r:any){const key=String(r.id||r.request_id),fd=new FormData(),n=notes[key]||"",f=files[key];if(n.trim())fd.append("response_note",n);if(f)fd.append("file",f);try{await api("/api/v1/claims/"+ticket+"/requests/"+key+"/respond",{method:"POST",body:fd});setD(await api("/api/v1/claims/"+ticket));setNotes({...notes,[key]:""});setFiles({...files,[key]:null})}catch(e:any){setError(e.message)}}return <Page title="Adjuster requests" subtitle="Respond to requests and provide documentation for the assigned adjuster." actions={<Link className="btn" href={"/claims/"+ticket}>Claim overview</Link>}>{error&&<div className="error">{error}</div>}<Card>{req.length?req.map((r:any)=>{const k=String(r.id||r.request_id);return <div className="dossier-section" key={k}><div className="section-head"><div className="list-main"><b>{r.request_text||r.description||"Information requested"}</b><span>{human(r.status||"open")} {r.responded_at?"· Responded "+dt(r.responded_at):""}</span></div><DataBadge status={r.status||"open"}/></div>{r.status==="open"&&<><textarea value={notes[k]||""} onChange={e=>setNotes({...notes,[k]:e.target.value})} placeholder="Your response…"/><div className="actions" style={{marginTop:8}}><label className="btn">Attach<input type="file" hidden onChange={e=>setFiles({...files,[k]:e.target.files?.[0]||null})}/></label><button className="btn primary" onClick={()=>respond(r)} disabled={!notes[k]?.trim()&&!files[k]}><Send size={14}/>Send to adjuster</button></div></>}</div>}):<Empty text="No adjuster requests recorded."/>}</Card></Page>}

export { Policies, LinkPolicy, Claims, Track, ClaimDetail, Evidence, Messages };
