"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BookOpen, Pencil, Search, Upload, X } from "lucide-react";
import { api } from "@/lib/api";
import { Card, DataBadge, Empty, Page } from "@/app-components/ui";

const human=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,m=>m.toUpperCase());

function Knowledge({manage=false}:{manage?:boolean}){
 const[q,setQ]=useState(""),[rows,setRows]=useState<any[]>([]),[docs,setDocs]=useState<any[]>([]),[msg,setMsg]=useState(""),[error,setError]=useState(""),[name,setName]=useState(""),[text,setText]=useState(""),[file,setFile]=useState<File|null>(null),[replaceFile,setReplaceFile]=useState<Record<string,File|null>>({}),[id,setId]=useState(""),[docType,setDocType]=useState("policy_wording"),[insuranceType,setInsuranceType]=useState("general"),[policyNumber,setPolicyNumber]=useState(""),[jurisdiction,setJurisdiction]=useState(""),[version,setVersion]=useState(""),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false);
 async function search(){setError("");try{const x=await api<any>("/api/v1/knowledge/search?q="+encodeURIComponent(q)+"&document_type="+encodeURIComponent(docType||""));setRows(x.items||[])}catch(e:any){setError(e.message)}}
 async function loadDocs(){try{const x=await api<any>("/api/v1/knowledge/documents");setDocs(x.items||[])}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(manage)loadDocs()},[manage]);
 async function ingestText(){setBusy(true);setError("");try{const x=await api<any>("/api/v1/knowledge/documents",{method:"POST",body:JSON.stringify({text,source_name:name,document_type:docType,insurance_type:insuranceType,policy_number:policyNumber||undefined,policy_version:version||undefined,jurisdiction:jurisdiction||undefined})});setId(x.document_id||"");setMsg("Document indexed successfully.");setText("");setName("");await loadDocs()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function upload(){if(!file)return;setBusy(true);setError("");try{const fd=new FormData();fd.append("file",file);fd.append("document_type",docType);fd.append("insurance_type",insuranceType);if(policyNumber)fd.append("policy_number",policyNumber);if(version)fd.append("policy_version",version);if(jurisdiction)fd.append("jurisdiction",jurisdiction);const x=await api<any>("/api/v1/knowledge/upload",{method:"POST",body:fd});setId(x.job_id||"");setMsg("Upload queued for indexing.");if(x.job_id){let done=false;for(let attempt=0;attempt<30&&!done;attempt++){await new Promise(res=>setTimeout(res,1000));const s=await api<any>("/api/v1/knowledge/ingestion/"+x.job_id);if(["processed","completed","dead_letter"].includes(s.status)){done=true;setMsg(s.status==="dead_letter"?"Indexing failed: "+(s.error||"worker rejected the document."):"Document indexing completed.")}}}await loadDocs()}catch(e:any){setError(e.message)}finally{setBusy(false);setFile(null)}}
 async function publish(docId:string){try{await api("/api/v1/knowledge/documents/"+docId+"/publish",{method:"POST"});setMsg("Document published.");await loadDocs()}catch(e:any){setError(e.message)}}
 async function updateDoc(){if(!editing)return;setBusy(true);try{await api("/api/v1/knowledge/documents/"+editing.id,{method:"PUT",body:JSON.stringify({source_name:editing.source_name,insurance_type:editing.insurance_type,policy_number:editing.policy_number,policy_version:editing.policy_version,jurisdiction:editing.jurisdiction,publication_status:editing.publication_status})});setMsg("Document metadata updated.");setEditing(null);await loadDocs()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function reindex(doc:any){setBusy(true);setError("");try{const x=await api<any>("/api/v1/knowledge/documents/"+doc.id+"/reindex",{method:"POST"});setMsg("Re-indexed "+(x.chunks||0)+" chunks.");await loadDocs()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function replaceContent(doc:any){
  const f=replaceFile[doc.id];
  if(!f)return;
  setBusy(true);setError("");
  try{
   const fd=new FormData();fd.append("file",f);fd.append("document_type",doc.document_type);if(doc.insurance_type)fd.append("insurance_type",doc.insurance_type);if(doc.policy_number)fd.append("policy_number",doc.policy_number);if(doc.policy_version)fd.append("policy_version",doc.policy_version);if(doc.jurisdiction)fd.append("jurisdiction",doc.jurisdiction);
   const x=await api<any>("/api/v1/knowledge/documents/"+doc.id+"/content",{method:"PUT",body:fd});
   setMsg("Document replaced and indexed. New document: "+(x.replacement_document_id||"created"));
   setReplaceFile(v=>({...v,[doc.id]:null}));
   await loadDocs();
  }catch(e:any){setError(e.message)}
  finally{setBusy(false)}
 }
 if(manage)return <Page title="Knowledge management" subtitle="Maintain policy wording and regulatory source documents used by claim intake and Copilot." actions={<Link className="btn" href="/knowledge"><BookOpen size={13}/>Search knowledge</Link>}>
  {(msg||error)&&<div className={error?"error":"notice"} role={error?"alert":"status"}>{error||msg}</div>}
  <div className="grid grid-2">
   <Card><div className="card-title">Create / index source</div><div className="form-grid"><label>Document type<select value={docType} onChange={e=>setDocType(e.target.value)}><option value="policy_wording">Policy wording</option><option value="regulation">Regulation</option><option value="guideline">Regulatory guidance</option><option value="claim_requirement">Claim requirements</option></select></label><label>Insurance type<input value={insuranceType} onChange={e=>setInsuranceType(e.target.value)} placeholder="motor, health…"/></label><label>Policy number<input value={policyNumber} onChange={e=>setPolicyNumber(e.target.value)}/></label><label>Version<input value={version} onChange={e=>setVersion(e.target.value)}/></label><label>Jurisdiction<input value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}/></label></div><label style={{marginTop:12}}>Source name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Policy wording or regulator title"/></label><label style={{marginTop:12}}>Text content<textarea value={text} onChange={e=>setText(e.target.value)} style={{minHeight:150}}/></label><div className="actions" style={{marginTop:10}}><button className="btn primary" onClick={ingestText} disabled={busy||text.trim().length<20||!name.trim()}>{busy?"Indexing…":"Index text source"}</button></div></Card>
   <Card><div className="card-title">Upload source file</div><label>Select PDF / DOCX / TXT<input type="file" accept=".pdf,.doc,.docx,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="btn primary" onClick={upload} disabled={busy||!file} style={{marginTop:12}}><Upload size={13}/>{busy?"Processing…":"Upload and index"}</button><div className="card-kicker" style={{marginTop:10}}>Files are malware-scanned, stored privately, queued through the transactional outbox, and indexed before publication.</div></Card>
  </div>
  <Card className="dossier-section"><div className="section-head"><div className="card-title" style={{margin:0}}>Source registry</div><button className="btn" onClick={loadDocs}>Refresh</button></div>{docs.length?<div className="table-wrap"><table><thead><tr><th>Source</th><th>Type</th><th>Version</th><th>Status</th><th>Chunks</th><th/></tr></thead><tbody>{docs.map((d:any)=><tr key={d.id}><td><b>{d.source_name}</b><div className="kpi-note">{d.policy_number||"General"} · {d.jurisdiction||"All jurisdictions"}</div></td><td>{human(d.document_type)}</td><td>{d.policy_version||"—"}</td><td><DataBadge status={d.publication_status||"pending_review"}/></td><td>{d.chunks||0}</td><td><div className="actions"><button className="btn" onClick={()=>setEditing({...d})}><Pencil size={12}/>Edit</button><button className="btn" onClick={()=>reindex(d)} disabled={busy}>Re-index</button><label className="btn">Replace<input type="file" hidden accept=".pdf,.doc,.docx,.txt" onChange={e=>setReplaceFile({...replaceFile,[d.id]:e.target.files?.[0]||null})}/></label>{replaceFile[d.id]&&<button className="btn" onClick={()=>replaceContent(d)} disabled={busy}>Apply replacement</button>}{d.publication_status!=="published"&&<button className="btn primary" onClick={()=>publish(d.id)}>Publish</button>}</div></td></tr>)}</tbody></table></div>:<Empty text="No knowledge sources have been indexed yet."/>}</Card>
  {editing&&<Card className="dossier-section"><div className="section-head"><div className="card-title" style={{margin:0}}>Update source metadata</div><button className="icon-btn" onClick={()=>setEditing(null)}><X size={14}/></button></div><div className="form-grid"><label>Source name<input value={editing.source_name||""} onChange={e=>setEditing({...editing,source_name:e.target.value})}/></label><label>Insurance type<input value={editing.insurance_type||""} onChange={e=>setEditing({...editing,insurance_type:e.target.value})}/></label><label>Policy number<input value={editing.policy_number||""} onChange={e=>setEditing({...editing,policy_number:e.target.value})}/></label><label>Version<input value={editing.policy_version||""} onChange={e=>setEditing({...editing,policy_version:e.target.value})}/></label><label>Jurisdiction<input value={editing.jurisdiction||""} onChange={e=>setEditing({...editing,jurisdiction:e.target.value})}/></label><label>Publication status<select value={editing.publication_status||"pending_review"} onChange={e=>setEditing({...editing,publication_status:e.target.value})}><option value="pending_review">Pending review</option><option value="published">Published</option><option value="superseded">Superseded</option><option value="archived">Archived</option></select></label></div><div className="actions" style={{marginTop:12}}><button className="btn primary" onClick={updateDoc} disabled={busy}>{busy?"Saving…":"Save metadata"}</button><button className="btn" onClick={()=>setEditing(null)}>Cancel</button></div></Card>}
 </Page>;
 return <Page title="Policy & Regulations" subtitle="Search published insurance knowledge used by claim intake and Copilot." actions={<Link className="btn" href="/knowledge/manage"><Pencil size={13}/>Manage knowledge</Link>}><Card><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search policy wording, regulations…"/><button className="btn primary" onClick={search}><Search size={13}/>Search</button></div>{error&&<div className="error" style={{marginTop:10}}>{error}</div>}{rows.length?rows.map((x:any,i:number)=><div className="list-row" key={x.id||i}><div className="list-main"><b>{x.title||x.document_name||x.source_name||"Knowledge result"}</b><span>{x.citation_label||x.snippet||x.content||x.text||""}</span></div><DataBadge status={x.document_type||"source"}/></div>):<Empty text={q?"No matching published sources.":"Search the policy knowledge base."}/>}</Card></Page>
}

export { Knowledge };
