"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import { Bell, CircleHelp, LogOut, Menu, Search, Settings } from "lucide-react";
import { api } from "@/lib/api";
import { assertWebAuthnSupport, prepareCreationOptions, prepareRequestOptions, serializeCredential } from "@/lib/webauthn";
import { Card, Empty, Page } from "@/app-components/ui";
import { ClaimantChat } from "@/app-components/claimant-chat";
import { AdjusterOnboardingPage } from "@/app-components/adjuster-onboarding";
import { AdjusterDashboard, AdjusterQueue, Workbench } from "@/app-components/adjuster-workspace";
import { AdminDashboard, Admin, AdminClaims, Audit } from "@/app-components/admin-workspace";
import { Policies, LinkPolicy, Claims, Track, ClaimDetail, Evidence, Messages } from "@/app-components/claimant-workspace";
import { Knowledge } from "@/app-components/knowledge-workspace";
import { EmailVerificationPage } from "@/app-components/email-verification";

type User={id:string;full_name?:string;email:string;role:"CLAIMANT"|"ADJUSTER"|"ADMIN";status?:string};
const first=(u:User)=>((u.full_name||u.email||"U")[0]||"U").toUpperCase();

function Auth({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <main className="login-page"><div className="auth-card"><div className="auth-brand"><span className="brand-mark">F</span><span>Flowa</span></div><h1 className="auth-title">{title}</h1><p className="auth-subtitle">{subtitle}</p>{children}</div></main>}

export function RegisterPage(){
 const router=useRouter(),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await api<any>("/api/v1/auth/signup",{method:"POST",body:JSON.stringify({full_name:fullName,email,phone,password,confirm_password:confirm})});if(r.email_verification_required){router.replace("/verify-email?email="+encodeURIComponent(email));return;}setMessage("Account created successfully.");setTimeout(()=>router.replace("/login"),700);}catch(e:any){setError(e.message||"Unable to create your account.")}finally{setBusy(false)}}
 return <Auth title="Create your claimant account" subtitle="Register securely to start and track insurance claims."><form className="form" onSubmit={submit}><label>Full name<input value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Phone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" minLength={8} required/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" minLength={8} required/></label>{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}<button className="btn primary" type="submit" disabled={busy}>{busy?"Creating account…":"Create account"}</button><div className="auth-links"><Link href="/login">Already have an account? Sign in</Link><span>Claimant account</span></div></form></Auth>
}

export function LoginPage(){
 const router=useRouter(),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[challenge,setChallenge]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[passkeyBusy,setPasskeyBusy]=useState(false);
 async function finish(r:any){if(!r?.access_token)throw Error("Authentication did not return an access token.");localStorage.setItem("access_token",r.access_token);const u=await api<User>("/api/v1/auth/me");router.replace(u.role==="ADJUSTER"?"/adjuster":u.role==="ADMIN"?"/admin":"/");}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{if(challenge){const r=await api<any>("/api/v1/auth/mfa/verify",{method:"POST",body:JSON.stringify({challenge_token:challenge,code})});if(r.user?.role==="ADMIN"||r.user?.role==="ADJUSTER"){await finish(r);return;}await finish(r);return;}const r=await api<any>("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})});if(r.mfa_required){setChallenge(r.challenge_token||r.challenge||"");return;}if(r.user?.role==="ADMIN"||r.user?.role==="ADJUSTER"){await finish(r);return;}await finish(r);}catch(e:any){setError(e.message||"Unable to sign in.")}finally{setBusy(false)}}
 async function enrollAndAuthenticatePasskey(){assertWebAuthnSupport();const options=await api<any>("/api/v1/auth/passkey/registration/options",{method:"POST"});const credential=await navigator.credentials.create({publicKey:prepareCreationOptions(options.public_key)});if(!credential)throw Error("Passkey registration was cancelled.");await api("/api/v1/auth/passkey/registration/verify",{method:"POST",body:JSON.stringify({challenge_id:options.challenge_id,credential:serializeCredential(credential as PublicKeyCredential)})});await signInWithPasskey();}
 async function signInWithPasskey(){setPasskeyBusy(true);setError("");try{assertWebAuthnSupport();if(!email.trim())throw Error("Enter your work email before using a passkey.");const options=await api<any>("/api/v1/auth/passkey/auth/options",{method:"POST",body:JSON.stringify({email})});const credential=await navigator.credentials.get({publicKey:prepareRequestOptions(options.public_key)});if(!credential)throw Error("Passkey authentication was cancelled.");const r=await api<any>("/api/v1/auth/passkey/auth/verify",{method:"POST",body:JSON.stringify({email,challenge_id:options.challenge_id,credential:serializeCredential(credential as PublicKeyCredential)})});await finish(r);}catch(e:any){setError(e.message||"Unable to authenticate with passkey.")}finally{setPasskeyBusy(false)}}
 return <Auth title={challenge?"Verify your identity":"Sign in"} subtitle={challenge?"Enter the one-time authenticator code.":"Access the secure insurance claims workspace."}><form className="form" onSubmit={submit}>{!challenge?<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label></>:<label>Authenticator code<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,8))} autoComplete="one-time-code" required/></label>}{error&&<div className="error" role="alert">{error}</div>}<button className="btn primary" type="submit" disabled={busy||passkeyBusy}>{busy?"Working…":challenge?"Verify and continue":"Sign in"}</button>{!challenge&&<button className="btn" type="button" onClick={signInWithPasskey} disabled={busy||passkeyBusy}>{passkeyBusy?"Waiting for passkey…":"Sign in with passkey"}</button>}{!challenge&&<div className="auth-links"><Link href="/register">Create claimant account</Link><Link href="/recovery">Forgot password?</Link><span>MFA protected</span></div>}</form></Auth>
}
export function RecoveryPage(){
 const [step,setStep]=useState(0),[email,setEmail]=useState(""),[otp,setOtp]=useState(""),[token,setToken]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[msg,setMsg]=useState(""),[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setError("");setMsg("");try{if(step===0){const r=await api<any>("/api/v1/auth/forgot-password",{method:"POST",body:JSON.stringify({email})});setMsg(r.message||"Code sent.");setStep(1)}else if(step===1){const r=await api<any>("/api/v1/auth/verify-otp",{method:"POST",body:JSON.stringify({email,otp})});setToken(r.reset_token||r.token||"");setStep(2)}else{await api("/api/v1/auth/reset-password",{method:"POST",body:JSON.stringify({reset_token:token,new_password:password,confirm_password:confirm})});setMsg("Password reset successfully.")}}catch(e:any){setError(e.message)}}
 return <Auth title="Account recovery" subtitle="Recover access with a verified one-time code."><form className="form">{step===0&&<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>}{step===1&&<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Verification code<input value={otp} onChange={e=>setOtp(e.target.value)} required/></label></>}{step===2&&<><label>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label></>}{error&&<div className="error">{error}</div>}{msg&&<div className="notice">{msg}</div>}{step===2&&msg?<Link className="btn primary" href="/login">Return to sign in</Link>:<button className="btn primary" onClick={submit}>{step===0?"Send code":step===1?"Verify code":"Reset password"}</button>}<div className="auth-links"><Link href="/login">Back to sign in</Link><span>Secure recovery</span></div></form></Auth>
}

type Nav={href:string;label:string;icon:LucideIcon;exact?:boolean};
function NavItem({n,p}:{n:Nav;p:string}){const active=n.exact?p===n.href:p===n.href||p.startsWith(n.href+"/"),I=n.icon;return <Link className={"nav-link"+(active?" active":"")} href={n.href}><I size={17}/><span>{n.label}</span></Link>}

function useUser(){
 const router=useRouter(),[u,setU]=useState<User|null|undefined>(undefined);
 useEffect(()=>{if(!localStorage.getItem("access_token")){router.replace("/login");return}let alive=true;api<User>("/api/v1/auth/me").then(x=>alive&&setU(x)).catch(()=>{localStorage.removeItem("access_token");if(alive) router.replace("/login")});return()=>{alive=false}},[router]);return u;
}

function WorkspaceShell(){
 const path=usePathname()||"/",router=useRouter(),user=useUser(),[open,setOpen]=useState(false),[offline,setOffline]=useState(false);
 useEffect(()=>{const a=()=>setOffline(false),b=()=>setOffline(true);window.addEventListener("online",a);window.addEventListener("offline",b);setOffline(!navigator.onLine);return()=>{window.removeEventListener("online",a);window.removeEventListener("offline",b)}},[]);
 useEffect(()=>{if(!user)return;const allowed=user.role==="CLAIMANT"?["/chat","/policies","/claims","/track","/settings"]:user.role==="ADJUSTER"?["/adjuster","/adjuster/queue","/policies","/knowledge","/settings"]:["/admin","/admin/audit","/claims","/settings"];if(user.role==="CLAIMANT"&&path==="/"){router.replace("/chat");return;}const ok=allowed.some(x=>path===x||path.startsWith(x+"/"));if(!ok)router.replace(user.role==="ADJUSTER"?"/adjuster":user.role==="ADMIN"?"/admin":"/chat")},[user,path,router]);
 if(!user)return <div className="login-page"><div className="auth-card"><div className="auth-brand"><span className="brand-mark">F</span><span>Flowa</span></div><div className="card-kicker">Loading secure workspace…</div></div></div>;
 if(user.role==="CLAIMANT" && (path==="/" || path==="/chat")) return <ClaimantChat/>;
 const claimant:Nav[]=[{href:"/chat",label:"Chat",icon:MessageCircle,exact:true},{href:"/policies",label:"Policies",icon:ShieldCheck},{href:"/claims",label:"Claims",icon:ClipboardList},{href:"/track",label:"Track Claims",icon:Activity}],adjuster:Nav[]=[{href:"/adjuster",label:"Overview",icon:LayoutDashboard,exact:true},{href:"/adjuster/queue",label:"Claims Queue",icon:ClipboardList},{href:"/policies",label:"Policy & Regulations",icon:ShieldCheck},{href:"/knowledge",label:"Knowledge Search",icon:BookOpen},{href:"/knowledge/manage",label:"Manage Knowledge",icon:FilePlus2}],admin:Nav[]=[{href:"/admin",label:"Administration",icon:Users,exact:true},{href:"/claims",label:"Claims",icon:ClipboardList},{href:"/admin/audit",label:"System Audit",icon:Activity}],nav=user.role==="ADJUSTER"?adjuster:user.role==="ADMIN"?admin:claimant;
 async function logout(){try{await api("/api/v1/auth/logout",{method:"POST"})}catch { /* best-effort cleanup */ }localStorage.removeItem("access_token");router.replace("/login")}
 return <div className="app-shell"><button className="mobile-menu" onClick={()=>setOpen(v=>!v)} aria-label="Open navigation"><Menu size={18}/></button>{open&&<div className="overlay" onClick={()=>setOpen(false)}/>}<aside className={"sidebar"+(open?" open":"")}><div className="brand"><span className="brand-mark">F</span><span>Flowa</span></div><div className="nav-group"><div className="nav-label">{user.role==="ADJUSTER"?"Adjuster workspace":user.role==="ADMIN"?"Administration":"My account"}</div>{nav.map(n=><NavItem key={n.href} n={n} p={path}/>)}</div><div className="side-bottom"><Link className="nav-link" href="/settings"><CircleHelp size={17}/><span>Help Center</span></Link><Link className="nav-link" href="/settings"><Settings size={17}/><span>Settings</span></Link><button className="nav-link" onClick={logout} style={{border:0,background:"transparent",textAlign:"left"}}><LogOut size={17}/><span>Sign out</span></button></div></aside><div className="main-area"><header className="topbar"><div className="searchbox"><Search size={16}/><input aria-label="Search workspace" placeholder="Search"/></div><div className="head-actions"><button className="icon-btn" aria-label="Notifications"><Bell size={17}/></button><Link className="profile" href="/settings"><span className="avatar">{first(user)}</span><span className="profile-meta"><b>{user.full_name||user.email}</b><span>{user.role==="ADJUSTER"?"Claims Adjuster":user.role==="ADMIN"?"Administrator":"Policy Holder"}</span></span></Link></div></header>{offline&&<div className="offline">You are offline. Existing data remains visible; submissions require an active connection.</div>}<section className="content"><Screen p={path} user={user}/></section></div></div>
}

function SettingsScreen({u}:{u:User}){const [passkey,setPasskey]=useState<{enabled:boolean;registered:boolean;credential_count:number}|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");useEffect(()=>{api<any>("/api/v1/auth/passkey/status").then(setPasskey).catch(()=>setPasskey(null))},[]);async function registerPasskey(){setBusy(true);setMsg("");setError("");try{assertWebAuthnSupport();const options=await api<any>("/api/v1/auth/passkey/registration/options",{method:"POST"});const credential=await navigator.credentials.create({publicKey:prepareCreationOptions(options.public_key)});if(!credential)throw Error("Passkey registration was cancelled.");await api("/api/v1/auth/passkey/registration/verify",{method:"POST",body:JSON.stringify({challenge_id:options.challenge_id,credential:serializeCredential(credential as PublicKeyCredential)})});setMsg("Passkey registered successfully.");setPasskey(prev=>({...prev,enabled:true,registered:true,credential_count:(prev?.credential_count||0)+1}));}catch(e:any){setError(e.message||"Unable to register passkey.")}finally{setBusy(false)}}return <Page title="Settings" subtitle="Account and secure session information."><div className="grid grid-2"><Card><div className="card-title">Profile</div><div className="detail-grid"><div className="detail-item"><span>Name</span><b>{u.full_name||"—"}</b></div><div className="detail-item"><span>Email</span><b>{u.email}</b></div><div className="detail-item"><span>Role</span><b>{u.role}</b></div></div></Card><Card><div className="card-title">Security</div><p className="kpi-note">Passkeys provide phishing-resistant authentication for privileged accounts.</p>{passkey?.registered?<div className="notice">Passkey registered ({passkey.credential_count}).</div>:<button className="btn primary" onClick={registerPasskey} disabled={busy}>{busy?"Registering…":"Register a passkey"}</button>}{error&&<div className="error" role="alert">{error}</div>}{msg&&<div className="notice">{msg}</div>}<Link className="btn" href="/recovery">Account recovery</Link></Card></div></Page>}
function Screen({p,user}:{p:string;user:User}){if(p==="/")return <ClaimantChat/>;if(p==="/chat")return <ClaimantChat/>;if(p==="/policies")return <Policies/>;if(p==="/policies/link")return <LinkPolicy/>;if(p==="/claims")return user.role==="ADMIN"?<AdminClaims/>:<Claims/>;if(p==="/track")return <Track/>;if(p==="/voice")return <ClaimantChat/>;if(p.startsWith("/voice/"))return <ClaimantChat/>;if(p.endsWith("/evidence")&&p.startsWith("/claims/"))return <Evidence ticket={decodeURIComponent(p.split("/")[2]||"")}/>;if(p.endsWith("/messages")&&p.startsWith("/claims/"))return <Messages ticket={decodeURIComponent(p.split("/")[2]||"")}/>;if(p.startsWith("/claims/"))return <ClaimDetail ticket={decodeURIComponent(p.split("/")[2]||"")}/>;if(p==="/adjuster")return <AdjusterDashboard/>;if(p==="/adjuster/queue")return <AdjusterQueue/>;if(p.startsWith("/adjuster/claims/"))return <Workbench ticket={decodeURIComponent(p.split("/")[3]||"")}/>;if(p==="/knowledge")return <Knowledge/>;if(p==="/knowledge/manage")return <Knowledge manage/>;if(p==="/admin")return <Admin/>;if(p==="/admin/audit")return <Audit/>;if(p==="/settings")return <SettingsScreen u={user}/>;return <Page title="Not found" subtitle="This workspace page does not exist."><Card><Empty text="Use the workspace navigation."/><Link className="btn primary" href="/">Back to dashboard</Link></Card></Page>}

export function RouterView(){const p=usePathname()||"/";if(p==="/login")return <LoginPage/>;if(p==="/register")return <RegisterPage/>;if(p==="/verify-email")return <EmailVerificationPage/>;if(p==="/recovery")return <RecoveryPage/>;if(p==="/onboarding/adjuster")return <AdjusterOnboardingPage/>;return <WorkspaceShell/>}
